sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- yarn add polymer-cli
- polymer install --variants
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: lm9QwabnaoJmEskfEGJqcnf5R/0XNZXcg8YREYAcNLRgXBZzhp4pXB2QBcqw4rRf9CT7qdN3J67bBUZl/Nf6JbyaCTalbxy8pxXPUM+T3Gj0jgNSDIFIz0UuO3qKVDZkcXAOLXjjLc+8q1GleiBoIAgsTpkDmdQ9I2d493hcFa1EQLl3BPb/T7jLw2jKR50+Kud4b5RW7rsajNSYzdJ63AxwyAyUECwGBQtRujQ3nXrUYBNyK+7ZxtlEpsUomYX2/Q08U2pjNHNgAClNN674RycoAf/RXcTnjWrExWqqhn4sls7+XE3Np1xvq7P9lT5FlyCD4qrnl6XlwAsPByKCwNd3UWRCGc6HholhiMxMPXkiFOp5/Z1G+NrQAi7JR4tNj0KTQXmXDZpFq2rKjk7yV2iN/2jD6vLCE0rCnyJuBIH+HT3RaUqrfo53J2bENKEc0ML2Z4Kx4S0OWOkzZ/MP0AEdUEAU2SMNzMNS/SpaUDtdYPLnzTvmV9neRurFgLUtzNkMVAZz24nMpSfwnGs4Mqszn8fUbBPgdoYF8Hd1hkgjowsx55mdCFcJGQDitpPDAaStuc7NH6EGMsia7jsoU74aC2QaNYJnpZLcnTlVbG4Es7wmtAGheXhPORRg9hM15hIfuW7meqOX0d9ZYjvVOItnUY0LVJ5UseGuTSKjHL0=
  - secure: JcPOeohxZ/KNmhDc57OPNqudXVMgg2jOEJippH6Yl8WOxlj54KvRRvnVQsJXWvVk7KwEDIPXeFybSnNnyb5eo/K1XSUYlKzauckXBzerp0HaDvdIlXcr6/dOWIg8q2uhYhAMhTtEs5EE6y+wewt0dz2ZDgY+iRGwUHpzDdZo4kW/gCpQJ8j/Fud5pz39BPRFHh0Qw6whFjzqWbQqmoIyP7cic+XmXwQGtVkCjhLLnbvh8Idgf8yuEQWkctLYX7uBMHSL3VPgRiq3KF+0iskmbRtffNUKhwTldEnSnpZ4ZqSRjOMPI1KcMAvGcR66MzejgctF6fpyrPRiTJWKIgc6n5D6xZXFZYVQOtaZWg0fwgPKsFLAvgVX99BVLuwuurn9WmhipMG6VEwl+DhAvq421jPOV48lV9Qd7+ExKa9yUd2l63m5ZiTzjzX3ExfyOnh9+om0m5+W0PIrdYD95ea5F94ehixueQDQNarLQwiUVHnXsCCdOJJjMvSwK75Jsiw+tdc0TiprQXdET/AvDRT9WXdqN7Z+3w1+QN8v6hqgHPAJBlptQ9WLwJbaPdg26r+aTh1zpqzfPVP2GNiJYUFOPDczqahBbTB+DTG6G9X7ge+DmGwupEE+HNAGPmrKoXqhOc+7BXjzDH1SB2i7Ei4Q8syu8VhWzXQ2eZrQxCBLhYc=
  - secure: 0fB9n07okFblPfxA8a6tAulVSXJYFDdFg8/ekwvwgQvWI/Drls5LwwsRqlcOQXOFlmXW1hosfJBEY5EkC7yVMdJ5is80GpY79DaYmszw8kN/z81t6Yp+nSE5AsZjkfbL0BfV1TYTOdarJkbGEM30KMhhr6+S/SA9EfCj3roZME/3qQ6rzgxHLlhJtDkdp5w+BGiEOvu2iFe9ZTVVsFKFreDbdASGwLuaQkesHZ3XPhrG+nt0sts5v3CUHBbSsB74o81HLGRBPbqJOR4QHBGyykGfyCqtNb5Zi3MLlPnHKoWgwhDhfpf6xDJmupYK0FFLMFpw7aVB2FIiZaG9faE+jET0mOhGwaTt77rP9FFJS3Xyi/ak8+XcDXI3E6uKG1lfHLaeim9lLZjnwJUYaDEOBD/ObL1AwOGxXxp6aFhVdlk2EtGWwdOQo9mbLc5FQGmJw4PLOTHEzeBv4neb3caPcQEhAhERMYAMUq+hi4nPiJZiRaA77t4x0DhRzswDuA23UYnZnxyvYpmkP3/RBouSa4r+agfX3CRnuqZ1XhHRJxxfVI9z0joXQBPZbBv135FhIs9y76auEbqqQhATz/b5TwuEhLHnwc3oNleuYi0PRbg8jkwKaFn3b1nk/9qj71i0alFhf7BYUKB1dygwABzP0hke68X494DosS8l4TW2bII=
  - secure: G8uu5WmhWqelki80YP2RasJEOpGI4XdeJxPZ2z/UZw0u4FqA0S1vrDY0tuWA3hVtkefuz6LvE5vvmG69ELia1SwjexuKTnr7LqzfwsEdws1SrE118CV2AehJNrRevev/S+0S6kgkxtyAEsKWynJckc/35Y/02SjQD8zWDPdw0CvudRHKUPunj17siuHb+XnbqshloFEJiV2LD7Qh3lmgDBMoVXvyYH1a/mYgmyaNswRFHvRFKl+7J5jABfRufqxsploW8kDGIR7Sgg2YrWRtGqIpNV7zYTGtle1nF/lv1FQpIq9iZb98gA9STQ4U8azHszNm30dYObkYvDeKkxMNjeaQbuKi6EkrMuWUio40wcok0rsVKUtFdAN+dIVfnQ41KU/5jmRbw75qpcu4kbiUrt0frTE7ZD7k00xKomCAhVWzTfL93F2wdW+K7tzuDthL+Z/nmmr0PorkXlJfNjpVNcVFkpQjmO7Z3DwFDzfOgEOgZNDgLfx6InzsCOagPGK4G3qG8AKM9yiLRIuqmb48MXMtXGiVemJvHx3H/4HOmCZ0z55feu2RC193P2my0jzZOkKGsNt+pB5U7NUm0plghZMy6GZQkNTgVBiArgt2K9n6WSL647psdpgYojTsn77B0OucmIJOlomdhJzfr62lK3Ar46ZZrDOOnaU1XXmtb+U=
